name: Packer Template Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    name: packer-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: '1.9.0'  # You can specify your preferred Packer version here

      - name: Check Packer formatting
        run: |
          packer fmt -check aws-ami.pkr.hcl variable.pkvars.hcl
        continue-on-error: false

      - name: Validate Packer template
        run: |
          packer validate aws-ami.pkr.hcl variable.pkvars.hcl
        continue-on-error: false

#    This is packer_test