name: Build, Test, and Create Custom Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Run integration tests
        run: mvn integration-test

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-artifact
          path: target/*.jar

  build-custom-image:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: app-artifact

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: '1.9.0'

      - name: Create Packer variables file
        run: |
          cat <<EOT > variables.pkrvars.hcl
          aws_region = "${{ secrets.AWS_REGION }}"
          vpc_id = "${{ secrets.VPC_ID }}"
          subnet_id = "${{ secrets.SUBNET_ID }}"
          ami_users = ["${{ secrets.AWS_ACCOUNT_ID }}"]
          EOT

      - name: Build AMI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          packer init aws-ami.pkr.hcl
          packer build -var-file=variables.pkrvars.hcl aws-ami.pkr.hcl

      - name: Cleanup
        if: always()
        run: rm variables.pkrvars.hcl