name: Packer Template Validation

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - '**.pkr.hcl'
      - '.github/workflows/packer-validate.yml'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "1.9.4"

      - name: Initialize Packer Plugins
        id: init
        run: |
          cd packer
          packer init .
          packer plugins installed

      - name: Check Packer Format
        id: fmt
        run: |
          cd packer
          packer fmt -check .

      - name: Validate Packer Template
        id: validate
        run: |
          cd packer
          packer validate .