name: Packer Custom Image Build

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Packer
        uses: hashicorp/setup-packer@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: "21"
          distribution: "adopt"

      - name: Build with Maven
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: mvn clean install -DskipTests

      - name: Run tests
        run: mvn test

      - name: Build Packer Image
        working-directory: PKR
        env:
          PACKER_LOG: 1
        run: |
          packer init .
          packer validate -var="aws_region=${{ secrets.AWS_REGION }}" \
            -var="subnet_id=${{ secrets.SUBNET_ID }}" \
            -var='ami_users=["${{ secrets.AMI_USERS }}"]' \
            .
          packer build -var="aws_region=${{ secrets.AWS_REGION }}" \
            -var="subnet_id=${{ secrets.SUBNET_ID }}" \
            -var='ami_users=["${{ secrets.AMI_USERS }}"]' \
            .

      - name: Verify Build Status
        if: success()
        run: echo "Packer build completed successfully"

#This is the new packer builder.

