name: Build Packer AMI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'

env:
  PKR_VAR_aws_region: ${{ secrets.AWS_REGION }}
  PKR_VAR_subnet_id: ${{ secrets.SUBNET_ID }}
  PKR_VAR_ami_users: ${{ secrets.AMI_USERS }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Application
        working-directory: ./webApplication
        run: mvn clean package

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: '1.9.4'

      - name: Initialize Packer
        run: packer init .

      - name: Build AMI
        id: build-ami
        run: |
          packer build -var-file=packer-vars.pkrvars.hcl packer-template.pkr.hcl

      - name: Notify on Success
        if: success()
        run: |
          echo "✅ AMI build completed successfully"

      - name: Notify on Failure
        if: failure()
        run: |
          echo "❌ AMI build failed"
